# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 17:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20171029_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='name',
        ),
    ]
