# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-21 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20171029_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='house_photo',
            field=models.CharField(default='house photo', max_length=100),
        ),
        migrations.AddField(
            model_name='house',
            name='name',
            field=models.CharField(default='house name', max_length=50),
        ),
        migrations.AddField(
            model_name='planet',
            name='description',
            field=models.CharField(default='planet description', max_length=100),
        ),
        migrations.AddField(
            model_name='planet',
            name='description_long',
            field=models.CharField(default='planet description long', max_length=1000),
        ),
        migrations.AddField(
            model_name='planet',
            name='main_photo',
            field=models.CharField(default='planet main photo', max_length=100),
        ),
        migrations.AddField(
            model_name='planet',
            name='small_photo',
            field=models.CharField(default='planet small photo', max_length=100),
        ),
    ]
