# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-21 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_auto_20171121_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planet',
            name='main_photo',
            field=models.CharField(max_length=100),
        ),
    ]
